#! /usr/bin/env bash

./jade \
  -g jruby-openssl \
  -g json \
  -l $ANALYTICS_HOME/lib/operators/target/custom-cascading-operators-0.0.2.jar \
  -l $ANALYTICS_HOME/lib/operators/target/emr \
  $ANALYTICS_HOME/lib/jobs/helpers \
  $ANALYTICS_HOME/lib/ruby/fdo.rb \
  $ANALYTICS_HOME/lib/jobs/cascading/*/*.rb
